package ai.candidly.career.emailintake;

import java.time.Instant;
import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

import ai.candidly.career.domain.Candidate;
import ai.candidly.career.domain.JobPosting;
import ai.candidly.career.pipeline.InterviewMode;

/**
 * A persisted record of one classified email (the mock's Inbox history) plus, for an
 * interview invitation matched to a known application, an AI-drafted reply awaiting the
 * human review gate (the mock's separate email-approval screen). {@link #draftReplyText}
 * is generated by {@link EmailReplyDraftService} from already-structured facts only
 * (company/title/mode/suggested time) - never from {@link #rawEmailText} directly - the
 * same "never hand a model raw third-party text plus generation power" discipline
 * {@code GroundedResumeGenerator} already applies to job postings.
 */
@Entity
@Table(name = "email_intake_record")
public class EmailIntakeRecord {

    @Id
    @GeneratedValue
    private UUID id;

    @ManyToOne(optional = false)
    @JoinColumn(name = "candidate_id")
    private Candidate candidate;

    @ManyToOne
    @JoinColumn(name = "job_posting_id")
    private JobPosting jobPosting;

    @Column(nullable = false, columnDefinition = "text")
    private String rawEmailText;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private EmailType emailType;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private InterviewMode mode;

    private Instant suggestedScheduledAt;

    private UUID createdInterviewId;

    @Column(columnDefinition = "text")
    private String draftReplyText;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private EmailReviewStatus reviewStatus;

    @Column(columnDefinition = "text")
    private String finalReplyText;

    private Instant reviewedAt;

    @Column(columnDefinition = "text")
    private String reviewNote;

    @Column(nullable = false)
    private Instant classifiedAt;

    protected EmailIntakeRecord() {
        // JPA
    }

    public EmailIntakeRecord(Candidate candidate, JobPosting jobPosting, String rawEmailText, EmailType emailType,
            InterviewMode mode, Instant suggestedScheduledAt, UUID createdInterviewId, String draftReplyText,
            EmailReviewStatus reviewStatus) {
        this.candidate = candidate;
        this.jobPosting = jobPosting;
        this.rawEmailText = rawEmailText;
        this.emailType = emailType;
        this.mode = mode;
        this.suggestedScheduledAt = suggestedScheduledAt;
        this.createdInterviewId = createdInterviewId;
        this.draftReplyText = draftReplyText;
        this.reviewStatus = reviewStatus;
        this.classifiedAt = Instant.now();
    }

    public void approveSend(String note) {
        this.finalReplyText = this.draftReplyText;
        this.reviewStatus = EmailReviewStatus.APPROVED_SEND;
        this.reviewNote = note;
        this.reviewedAt = Instant.now();
    }

    public void editAndSend(String editedText, String note) {
        this.finalReplyText = editedText;
        this.reviewStatus = EmailReviewStatus.EDITED_SEND;
        this.reviewNote = note;
        this.reviewedAt = Instant.now();
    }

    public void schedule(String note) {
        this.finalReplyText = this.draftReplyText;
        this.reviewStatus = EmailReviewStatus.SCHEDULED;
        this.reviewNote = note;
        this.reviewedAt = Instant.now();
    }

    /** The candidate proposes a different time/format instead of sending the draft as-is -
     * still never sends anything, same as every other terminal status here. */
    public void suggestAlternative(String alternativeText, String note) {
        this.finalReplyText = alternativeText;
        this.reviewStatus = EmailReviewStatus.ALTERNATIVE_SUGGESTED;
        this.reviewNote = note;
        this.reviewedAt = Instant.now();
    }

    public void cancel(String note) {
        this.reviewStatus = EmailReviewStatus.CANCELLED;
        this.reviewNote = note;
        this.reviewedAt = Instant.now();
    }

    public UUID getId() {
        return id;
    }

    public Candidate getCandidate() {
        return candidate;
    }

    public JobPosting getJobPosting() {
        return jobPosting;
    }

    public String getRawEmailText() {
        return rawEmailText;
    }

    public EmailType getEmailType() {
        return emailType;
    }

    public InterviewMode getMode() {
        return mode;
    }

    public Instant getSuggestedScheduledAt() {
        return suggestedScheduledAt;
    }

    public UUID getCreatedInterviewId() {
        return createdInterviewId;
    }

    public String getDraftReplyText() {
        return draftReplyText;
    }

    public EmailReviewStatus getReviewStatus() {
        return reviewStatus;
    }

    public String getFinalReplyText() {
        return finalReplyText;
    }

    public Instant getReviewedAt() {
        return reviewedAt;
    }

    public String getReviewNote() {
        return reviewNote;
    }

    public Instant getClassifiedAt() {
        return classifiedAt;
    }
}
